---
- name: Create app directory
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose file
  copy:
    src: "{{ playbook_dir }}/../../docker-compose.yml"
    dest: "{{ app_dir }}/docker-compose.yml"
    mode: '0644'

- name: Create environment file from template
  template:
    src: .env.j2
    dest: "{{ app_dir }}/.env"
    mode: '0600'

- name: Create nginx directory
  file:
    path: "{{ app_dir }}/nginx"
    state: directory
    mode: '0755'

- name: Copy nginx config
  copy:
    src: "{{ playbook_dir }}/../../nginx/nginx.conf"
    dest: "{{ app_dir }}/nginx/nginx.conf"
    mode: '0644'

- name: Start containers
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    state: present
  register: output
